"""IC memo page — renders the memo generated by the main dashboard.

The memo is produced from the optimizer and Monte Carlo outputs when you press
RUN OPTIMIZATION on the main page; this page simply presents it, terminal-styled,
with a markdown download. Session state carries the results across pages.
"""

from __future__ import annotations

import streamlit as st

from src.terminal import CSS

st.set_page_config(page_title="IC Memo — StackOptimal", layout="wide")
st.markdown(f"<style>{CSS}</style>", unsafe_allow_html=True)

st.markdown(
    '<div class="statusbar"><span><span class="brand">STACKOPTIMAL</span>'
    " &nbsp;//&nbsp; IC MEMO</span><span>GENERATED FROM MODEL OUTPUTS</span></div>",
    unsafe_allow_html=True,
)

if "results" not in st.session_state:
    st.info("No deal in memory — run the optimizer on the main page first "
            "(fetch a target, press RUN OPTIMIZATION), then return here.")
    st.stop()

res = st.session_state.results
company = st.session_state.get("company")
if company is not None:
    st.markdown(
        f'<div class="rec-line">TARGET <b>{company.name.upper()}</b> ({company.ticker})'
        f" &nbsp;·&nbsp; {company.currency}mm THROUGHOUT</div>",
        unsafe_allow_html=True,
    )

st.markdown(res["memo"])
st.download_button("Download memo (markdown)", res["memo"], "ic_memo.md")
